# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "22881dbe27a8d3b77e03363958d0588d"
application_url = "https://wealth-qualifications-kent-map.trycloudflare.com"
embedded = true
name = "order-create-manual-zack"
handle = "order-create-manual-zack"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders,write_orders,read_customers,write_customers,read_draft_orders,write_draft_orders"

[auth]
redirect_urls = [
  "https://wealth-qualifications-kent-map.trycloudflare.com/auth/callback",
  "https://wealth-qualifications-kent-map.trycloudflare.com/auth/shopify/callback",
  "https://wealth-qualifications-kent-map.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
